---
- name: Setup Flask Application with Nginx
  hosts: all
  become: yes

  tasks:
    - name: Update the package cache
      apt:
        update_cache: yes

    # Install required packages
    - name: Install Nginx, Git, and Python packages
      apt:
        name:
          - nginx
          - git
          - python3
          - python3-pip
          - python3-venv
        state: present

    - name: Remove the default Nginx configuration
      file:
        path: /etc/nginx/sites-available/default
        state: absent
      become: yes
    - name: Remove the default Nginx symbolic link
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      become: yes

    # Create Nginx configuration file
    - name: Create Nginx configuration for Flask application
      copy:
        dest: /etc/nginx/conf.d/flask_app.conf
        content: |
          server {
              listen 80;
              server_name _;

              location / {
                  proxy_pass http://127.0.0.1:8080;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              }
          }
      notify:
        - Reload Nginx

    - name: Test Nginx configuration
      command: nginx -t
      become: yes

    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
      become: yes

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
